[package]
name = "simd_find_char"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { workspace = true }
rand = { workspace = true }
utils = { path="../utils"}

[[bench]]
name = "quote_bench"
harness = false
